# Generated by Django 6.0.1 on 2026-07-13 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_ma', models.IntegerField(default=0)),
                ('team_ona', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_main', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.IntegerField()),
                ('emtiaz_dast', models.IntegerField()),
                ('color', models.IntegerField()),
                ('emtiaz_ma', models.IntegerField()),
                ('emtiaz_ona', models.IntegerField()),
                ('team_ma', models.IntegerField()),
                ('team_ona', models.IntegerField()),
                ('yasa', models.BooleanField(default=False)),
                ('edit', models.BooleanField(default=False)),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_main', to='shelem.main')),
            ],
        ),
    ]
