# Generated by Django 6.0.1 on 2026-07-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='joker',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
