# Generated by Django 6.0.1 on 2026-07-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelem', '0002_main_joker'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='sh',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
