# Generated by Django 6.0.1 on 2026-07-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelem', '0003_main_sh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='sh',
        ),
        migrations.AddField(
            model_name='game',
            name='sh',
            field=models.BooleanField(default=False),
        ),
    ]
